---
version: "3.8"
services:
  movies:
    image: andrew2711/moviesrepo:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  
  train:
    image: andrew2711/trainrepo:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
    
  dth:
    image: andrew2711/dthrepo:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
    
  recharge:
    image: andrew2711/rechargerepo:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
   
